spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-service"
  application:
    name: customer-service
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: customer-service
      authentication-database: admin
keycloak:
  auth-server-url: http://localhost:9098
  realm: micro-service
  client-id: microservice-auth
  client-secret: AFzl9Z8apD0ggbcjilxEWWHMbARF1NIS

server:
  port: 8040

  # Endpoints
  token-uri: ${keycloak.auth-server-url}/realms/micro-service/protocol/openid-connect/token
  logout-uri: ${keycloak.auth-server-url}/realms/micro-service/protocol/openid-connect/logout
  admin-uri: ${keycloak.auth-server-url}/admin/realms/micro-service